### PR TITLE
add prototype design v. 0.1.

### PR DESCRIPTION
**Pull request by mshevko**

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
Снимок экрана 2020-03-03 в 17 55 48

**Comment by MaksimViarenich** [comment]
Снимок экрана 2020-03-03 в 17 58 49
How can I apply multiple search. Where can I type name and date?
I think that for tag search you also should use input, not dropdown. Because if it will be 1000 tags, you will show all of them?)

**Comment by MaksimViarenich** [comment]
Not in TR
Снимок экрана 2020-03-03 в 18 01 17

**Comment by MaksimViarenich** [comment]
It's better to have input for tags. And on edit mode, u will just change the value for this field

**Comment by MaksimViarenich** [comment]
In general, u did a good job!

**Comment by mshevko** [comment]
> In general, u did a good job!

thank you a lot !

**Pull request merged**
